const all = [
    "Allston",
    "Back Bay",
    "Bay Village",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Dottie",
    "Downtown",
    "East Boston",
    "Fenway",
    "Kenmore",
    "Longwood",
    "Harborlights",
    "Hyde Park",
    "Jamaica Plain",
    "Mattapan",
    "Mission Hill",
    "North End",
    "Roslindale",
    "Rozzie",
    "Roxbury",
    "Southie",
    "South End",
    "West End",
    "West Roxbury",
    "Wharf District",
    "Rose Wharf",
    "Cambridge",
    "Agassiz", 
    "Avon Hill", 
    "Cambridge Highlands", 
    "Cambridgeport", 
    "Central Square", 
    "East Cambridge", 
    "Harvard Square", 
    "Huron Village", 
    "Inman Square", 
    "Kendall Square", 
    "Larchwood",
    "MIT",
    "Mid Cambridge", 
    "Neighborhood Four", 
    "North Cambridge", 
    "Porter Square", 
    "Riverside", 
    "Strawberry Hill", 
    "Wellington Harrington", 
    "West Cambridge",
    "Somerville",
    "Winter Hill",
    "Assembly Square",
    "Ball Square",
    "Brickbottom",
    "Davis Square",
    "East Somerville",
    "Gilman Square",
    "Inner Belt District",
    "Magoun Square",
    "Powder House Square",
    "Boston",
    "Worcester",
    "Springfield",
    "Lowell",
    "New Bedford",
    "Brockton",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Waltham",
    "Haverhill",
    "Malden",
    "Medford",
    "Taunton",
    "Chicopee",
    "Weymouth",
    "Revere",
    "Peabody",
    "Methuen",
    "Barnstable",
    "Pittsfield",
    "Attleboro",
    "Everett",
    "Salem",
    "Westfield",
    "Leominster",
    "Fitchburg",
    "Beverly",
    "Holyoke",
    "Marlborough",
    "Woburn",
    "Chelsea",
    "Quincy Market",
    "Cedar Junction",
    "Plymouth",
    "Gillette Stadium",
    "Castle Island",
    "Charles River",
    "Neponset River",
    "Mashpee",
    "Sharon",
    "Walden",
    "Newbury",
    "Revere",
    "Nahant",
    "Tremont",
    "Forge Park",
    "Windsor Gardens",
    "Hampton Beach",
    "Hull",
    "Nantasket",
    "King Philip",
    "Islington",
    "Ruggles",
    "Endicott",
    "South Station",
    "Blue Hills",
    "Boylston",
    "Hanover",
    "Haymarket",
    "Jamaicaway",
    "Huntington Ave",
    "Mass Ave",
    "Pike",
    "Morrissey Boulevard",
    "Storrow Drive",
    "Soldiers Field Road",
    "Tremont",
    "VFW Parkway",
    "Washington Street",
    "Old Post Road",
    "Arborway",
    "Landsdowne",
    "Downtown Crossing",
    "Suffolk Downs",
    "Stony Brook",
    "Park Street",
    "Pru",
    "Symphony",
    "Brigham Circle",
    "Cleveland Circle",
    "Chesnut Hill",
    "Ashmont",
    "Jackson Square",
    "Uphams Corner",
    "Chelsea",
    "Arlingto n",
    "Hyde Park",
    "Savin Hill",
    "Copley",
    "Packards Corner",
    "Hynes",
    "Mattapan",
    "Fields Corner",
    "Alewife",
    "Wonderland",
    "Lechmere",
    "Canton",
    "Stoughton",
    "Forest Hills",
    "Silver Line",
    "Brookline",
    "Coolidge Corner",
    "Fresh Pond",
    "Billerica",
    "Lynn",
    "Merrimack",
    "Mystic River",
    "Chicopee",
    "Saugus",
    "Agawam",
    "Quabbin",
    "Jamaica Pond",
    "Arboretum",
    "Great Woods",
    "Dottie Pear",
    "Faneuil Hall",
    "Isabella Stewart Gardner",
    "Pru",
    "Common",
    "Franklin Park",
    "Brattle",
    "Esplanade",
    "Cape Cod",
    "Nantucket",
    "Martha's Vineyard",
    "Peggy Lawton",
    "Papagino",
    "Regina",
    "Dunkin",
    "Honeydew",
    "D'Angelo",
    "Frugal Fannie",
    "Bradlees",
    "Nabisco",
    "Necco",
    "Fluff",
    "Filenes",
    "Coolata",
    "Friendlys",
    "Fripple",
    "Dunkaccino",
    "Bertuccis",
    "Yankee Candle",
    "Ground Round",
    "Ninety Nine",
    "Building 19",
    "Cumberland Farms",
    "Fantastic Sams",
    "Jordans Furniture",
    "JP Licks",
    "Sam Adams",
    "Jordan Marsh",
    "Munchkins",
    "Ocean Spray",
    "Hoodsie",
    "Down Cellah",
    "Clam Chowdah",
    "Statie",
    "Baked Beans",
    "Frappe",
    "T",
    "Bubblah",
    "Wicked",
    "Fluffernutter",
    "Candlepin",
    "Pockabook",
    "Nomar",
    "Ortiz",
    "Susan Wornick",
    "Hank Phillipi",
    "Natalie Jacobson",
    "Chet Curtis",
    "Joe Shortsleeve",
    "Tom Brady",
    "Larry Bird",
    "Menino",
    "Barbara Walters",
    "Mark Wahlberg",
    "Donnie Wahlberg",
    "Ben Affleck",
    "Matt Damon",
    "Johnny Damon",
    "Ted Kennedy",
    "Pedro Martinez",
    "James Taylor",
    "Dropkick Murphys",
    "New Kids on the Block",
    "Aerosmith",
    "Paul Pierce",
    "Bobby Orr",
    "Cam Neely",
    "Drew Bledsoe",
    "Jerry Remy",
    "Ted Williams",
    "David Wade",
    "Maria Stephanos",
    "Al Kaprielian",
    "Bobby Brown",
    "Gene Lavanchy",
    "Minutemen",
    "John Hancock",
    "Whitey Bulger",
    "Arthur Fielder",
    "Red Sox",
    "Celtics",
    "Pats",
    "Bruins"
]