const local = [
    "Peggy Lawton",
    "Papagino",
    "Regina",
    "Dunkin",
    "Honeydew",
    "D'Angelo",
    "Frugal Fannie",
    "Bradlees",
    "Nabisco",
    "Necco",
    "Fluff",
    "Filenes",
    "Coolata",
    "Friendlys",
    "Fripple",
    "Dunkaccino",
    "Bertuccis",
    "Yankee Candle",
    "Ground Round",
    "Ninety Nine",
    "Building19",
    "Cumberland Farms",
    "Jordans",
    "JP Licks",
    "Sam Adams",
    "Jordan Marsh",
    "Munchkins",
    "Hoodsie",
    "Down Cellah",
    "Clam Chowdah",
    "Statie",
    "Baked Beans",
    "Frappe",
    "T",
    "Bubblah",
    "Wicked",
    "Fluffernutter",
    "Candlepin",
    "Pockabook",
    "Nomar",
    "Ortiz",
    // "Susan Wornick",
    // "Hank Phillipi",
    // "Joe Shortsleeve",
    "Brady",
    "Larry Bird",
    "Wahlberg",
    "Donnie",
    "Ben Affleck",
    "Damon",
    "Kennedy",
    "Pedro",
    "Dropkick",
    "New Kids",
    "Aerosmith",
    // "Paul Pierce",
    // "Bobby Orr",
    // "Cam Neely",
    "Brady",
    // "Jerry Remy",
    // "Ted Williams",
    // "Al Kaprielian",
    // "Gene Lavanchy",
    "Minutemen",
    "Hancock",
    "Red Sox",
    "Celtics",
    "Pats",
    "Bruins",
]