const local = [
    "Peggy Lawton",
    "Papagino",
    "Regina",
    "Dunkin",
    "Honeydew",
    "D'Angelo",
    "Frugal Fannie",
    "Bradlees",
    "Bickfords",
    "Nabisco",
    "Necco",
    "Fluff",
    "Filenes",
    "Coolata",
    "Friendlys",
    "Fribble",
    "Dunkaccino",
    "Bertuccis",
    "Yankee Candle",
    "Ground Round",
    "Building19",
    "Cumbies",
    "Jordans",
    "Sam Adams",
    "Jordan Marsh",
    "Munchkins",
    "Hoodsie",
    "Down Cellah",
    "Clam Chowdah",
    "Statie",
    "Baked Beans",
    "Frappe",
    "Bubblah",
    "Wicked",
    "Fluffernutter",
    "Candlepin",
    "Pockabook",
    "Nomar",
    "Ortiz",
    "Brady",
    "Larry Bird",
    "Wahlberg",
    "Donnie",
    "Ben Affleck",
    "Damon",
    "Kennedy",
    "Pedro",
    "Dropkick",
    "New Kids",
    "Aerosmith",
    "Minutemen",
    "Hancock",
    "Red Sox",
    "Celtics",
    "Pats",
    "Bruins",
    "T.",
    "'99'"
]