const local = [
    "Peggy Lawton",
    "Papagino",
    "Regina",
    "Dunkin",
    "Honeydew",
    "D'Angelo",
    "Frugal Fannie",
    "Bradlees",
    "Nabisco",
    "Necco",
    "Fluff",
    "Filenes",
    "Coolata",
    "Friendlys",
    "Fripple",
    "Dunkaccino",
    "Bertuccis",
    "Yankee Candle",
    "Ground Round",
    "Ninety Nine",
    "Building 19",
    "Cumberland Farms",
    "Fantastic Sams",
    "Jordans Furniture",
    "JP Licks",
    "Sam Adams",
    "Jordan Marsh",
    "Munchkins",
    "Ocean Spray",
    "Hoodsie",
    "Down Cellah",
    "Clam Chowdah",
    "Statie",
    "Baked Beans",
    "Frappe",
    "T",
    "Bubblah",
    "Wicked",
    "Fluffernutter",
    "Candlepin",
    "Pockabook",
    "Nomar",
    "Ortiz",
    "Susan Wornick",
    "Hank Phillipi",
    "Joe Shortsleeve",
    "Brady",
    "Larry Bird",
    "Mark Wahlberg",
    "Donnie Wahlberg",
    "Ben Affleck",
    "Matt Damon",
    "Johnny Damon",
    "Ted Kennedy",
    "Pedro",
    "James Taylor",
    "Dropkick Murphys",
    "New Kids on the Block",
    "Aerosmith",
    "Paul Pierce",
    "Bobby Orr",
    "Cam Neely",
    "Drew Bledsoe",
    "Brady",
    "Jerry Remy",
    "Ted Williams",
    "Al Kaprielian",
    "Bobby Brown",
    "Gene Lavanchy",
    "Minutemen",
    "Hancock",
    "Red Sox",
    "Celtics",
    "Pats",
    "Bruins",
    "Isabella Stewart Gardner"
]