const mass = [
    "Allston",
    "BackBay",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Dottie",
    "Downtown",
    "Eastie",
    "Fenway",
    "Kenmore",
    "Longwood",
    "Harborlights",
    "Hyde Park",
    "JP",
    "Mattapan",
    "North End",
    "Roslindale",
    "Rozzie",
    "Roxbury",
    "Southie",
    "South End",
    "Cambridge",
    "Central Square", 
    "Harvard Square", 
    "Kendall Square", 
    "Somerville",
    "Davis Square",
    "Boston",
    "Worcester",
    "Springfield",
    "Lowell",
    "Brockton",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Waltham",
    "Revere",
    "Peabody",
    "Barnstable",
    "Everett",
    "Salem",
    "Beverly",
    "Chelsea",
    "Cedar Junction",
    "Plymouth",
    "Gillette",
    "Castle Island",
    "Charles",
    "Neponset",
    "Mashpee",
    "Sharon",
    "Walden",
    "Newbury",
    "Revere",
    "Nahant",
    "Tremont",
    "Forge Park",
    "Windsor Gardens",
    "Hampton Beach",
    "Hull",
    "Nantasket",
    "King Philip",
    "Islington",
    "Ruggles",
    "Endicott",
    "South Station",
    "Blue Hills",
    "Boylston",
    "Haymarket",
    "Jamaicaway",
    "Huntington",
    "Mass",
    "Pike",
    "Storrow",
    "Tremont",
    "VFW Parkway",
    "Old Post",
    "Arborway",
    "Landsdowne",
    "Downtown Crossing",
    "Suffolk Downs",
    "Pru",
    "Symphony",
    "Brigham",
    "Ashmont",
    "Chelsea",
    "Arlington",
    "Copley",
    "Hynes",
    "Mattapan",
    "Alewife",
    "Wonderland",
    "Lechmere",
    "Forest Hills",
    "Silver Line",
    "Brookline",
    "Lynn",
    "Merrimack",
    "Agawam",
    "Quabbin",
    "Arboretum",
    "Great Woods",
    "Faneuil",
    "Common",
    "Franklin Park",
    "Brattle",
    "Esplanade",
    "Cape Cod",
    "Nantucket",
    "Martha's Vineyard",
    "Logan",
    "Paxton",
    "T.",
    "'99'",
    "Peggy Lawton",
    "Papagino",
    "Regina",
    "Dunkin",
    "Honeydew",
    "D'Angelo",
    "Frugal Fannie",
    "Bradlees",
    "Bickfords",
    "Nabisco",
    "Necco",
    "Fluff",
    "Filenes",
    "Coolata",
    "Friendlys",
    "Fribble",
    "Dunkaccino",
    "Bertuccis",
    "Yankee Candle",
    "Ground Round",
    "Building19",
    "Cumbies",
    "Jordans",
    "Sam Adams",
    "Jordan Marsh",
    "Munchkins",
    "Hoodsie",
    "Down Cellah",
    "Clam Chowdah",
    "Statie",
    "Baked Beans",
    "Frappe",
    "Bubblah",
    "Wicked",
    "Fluffernutter",
    "Candlepin",
    "Pockabook",
    "Nomar",
    "Ortiz",
    "Brady",
    "Larry Bird",
    "Wahlberg",
    "Ben Affleck",
    "Damon",
    "Kennedy",
    "Pedro",
    "Dropkick",
    "New Kids",
    "Aerosmith",
    "Brady",
    "Minutemen",
    "Hancock",
    "Red Sox",
    "Celtics",
    "Pats",
    "Bruins",
]