const middle = [
    "Honeydew",
    "Bradlees",
    "Bickfords",
    "Nabisco",
    "Necco",
    "Fluff",
    "Filenes",
    "Coolata",
    "Friendlys",
    "Fribble",
    "Dunkaccino",
    "Bertuccis",
    "Yankee Candle",
    "Ground Round",
    "Building19",
    "Cumbies",
    "Jordans",
    "Munchkins",
    "Hoodsie",
    "Down Cellah",
    "Clam Chowdah",
    "Statie",
    "Baked Beans",
    "Frappe",
    "Bubblah",
    "Wicked",
    "Fluffernutter",
    "Candlepin",
    "Pockabook",
    "Dropkick",
    "New Kids",
    "Aerosmith",
    "Minutemen",
    "Hancock",
    "Red Sox",
    "Celtics",
    "Pats",
    "Bruins",
    "T.",
    "'99'",
    "Allston",
    "Back Bay",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Eastie",
    "Fenway",
    "Kenmore",
    "Longwood",
    "Harborlights",
    "Hyde Park",
    "JP",
    "Mattapan",
    "North End",
    "Rozzie",
    "Roxbury",
    "Southie",
    "South End",
    "Cambridge",
    "Harvard", 
    "Somerville",
    "Boston",
    "Worcester",
    "Springfield",
    "Brockton",
    "Newton",
    "Lawrence",
    "Waltham",
    "Haverhill",
    "Medford",
    "Revere",
    "Barnstable",
    "Cedar Junction",
    "Plymouth",
    "Gillette",
    "Castle Island",
    "Charles",
    "Neponset",
    "Mashpee",
    "Sharon",
    "Walden",
    "Newbury",
    "Revere",
    "Nahant",
    "Tremont",
    "Forge Park",
    "Windsor Gardens",
    "Hampton Beach",
    "Hull",
    "Nantasket",
    "Islington",
    "Ruggles",
    "Endicott",
    "South Station",
    "Blue Hills",
    "Boylston",
    "Haymarket",
    "Jamaicaway",
    "Huntington",
    "Mass",
    "Pike",
    "Storrow",
    "Tremont",
    "VFW Parkway",
    "Old Post",
    "Arborway",
    "Landsdowne",
    "Downtown Crossing",
    "Suffolk Downs",
    "Pru",
    "Symphony",
    "Copley",
    "Hynes",
    "Mattapan",
    "Alewife",
    "Wonderland",
    "Lechmere",
    "Forest Hills",
    "Silver Line",
    "Brookline",
    "Coolidge Corner",
    "Billerica",
    "Mystic River",
    "Agawam",
    "Quabbin",
    "Arboretum",
    "Great Woods",
    "Faneuil Hall",
    "Common",
    "Franklin",
    "Brattle",
    "Esplanade",
    "Cape Cod",
    "Nantucket",
    
]