const places = [
    "Allston",
    "BackBay",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Dottie",
    "Downtown",
    "Eastie",
    "Fenway",
    "Kenmore",
    "Longwood",
    "Harborlights",
    "Hyde Park",
    "JP",
    "Mattapan",
    "North End",
    "Roslindale",
    "Rozzie",
    "Roxbury",
    "Southie",
    "South End",
    "Cambridge",
    "Central Square", 
    "Harvard Square", 
    "Kendall Square", 
    "Somerville",
    "Davis Square",
    "Boston",
    "Worcester",
    "Springfield",
    "Lowell",
    "New Bedford",
    "Brockton",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Waltham",
    "Haverhill",
    "Medford",
    "Revere",
    "Peabody",
    "Barnstable",
    "Pittsfield",
    "Attleboro",
    "Everett",
    "Salem",
    "Beverly",
    "Chelsea",
    "Quincy Market",
    "Cedar Junction",
    "Plymouth",
    "Gillette",
    "Castle Island",
    "Charles River",
    "Neponset",
    "Mashpee",
    "Sharon",
    "Walden",
    "Newbury",
    "Revere",
    "Nahant",
    "Tremont",
    "Forge Park",
    "Windsor Gardens",
    "Hampton Beach",
    "Hull",
    "Nantasket",
    "King Philip",
    "Islington",
    "Ruggles",
    "Endicott",
    "South Station",
    "Blue Hills",
    "Boylston",
    "Haymarket",
    "Jamaicaway",
    "Huntington",
    "Mass",
    "Pike",
    "Storrow",
    "Tremont",
    "VFW Parkway",
    "Old Post Road",
    "Arborway",
    "Landsdowne",
    "Downtown Crossing",
    "Suffolk Downs",
    "Pru",
    "Symphony",
    "Brigham",
    "Ashmont",
    "Chelsea",
    "Arlington",
    "Hyde Park",
    "Copley",
    "Hynes",
    "Mattapan",
    "Alewife",
    "Wonderland",
    "Lechmere",
    "Forest Hills",
    "Silver Line",
    "Brookline",
    "Coolidge Corner",
    "Fresh Pond",
    "Billerica",
    "Lynn",
    "Merrimack",
    "Mystic River",
    "Agawam",
    "Quabbin",
    "Jamaica Pond",
    "Arboretum",
    "Great Woods",
    "Faneuil Hall",
    "Common",
    "Franklin Park",
    "Brattle",
    "Esplanade",
    "Cape Cod",
    "Nantucket",
    "Martha's Vineyard",
    "Logan",
    "Paxton",
    "T.",
    "'99'"
]