const places = [
    "Allston",
    "Back Bay",
    "Bay Village",
    "Beacon Hill",
    "Brighton",
    "Charlestown",
    "Chinatown",
    "Dottie",
    "Downtown",
    "East Boston",
    "Fenway",
    "Kenmore",
    "Longwood",
    "Harborlights",
    "Hyde Park",
    "Jamaica Plain",
    "Mattapan",
    "Mission Hill",
    "North End",
    "Roslindale",
    "Rozzie",
    "Roxbury",
    "Southie",
    "South End",
    "West Roxbury",
    "Rose Wharf",
    "Cambridge",
    "Cambridgeport", 
    "Central Square", 
    "Harvard Square", 
    "Inman Square", 
    "Kendall Square", 
    "Porter Square", 
    "Somerville",
    "Winter Hill",
    "Assembly Square",
    "Ball Square",
    "Brickbottom",
    "Davis Square",
    "Gilman Square",
    "Magoun Square",
    "Powder House Square",
    "Boston",
    "Worcester",
    "Springfield",
    "Lowell",
    "New Bedford",
    "Brockton",
    "Quincy",
    "Lynn",
    "Fall River",
    "Newton",
    "Lawrence",
    "Waltham",
    "Haverhill",
    "Malden",
    "Medford",
    "Taunton",
    "Chicopee",
    "Weymouth",
    "Revere",
    "Peabody",
    "Methuen",
    "Barnstable",
    "Pittsfield",
    "Attleboro",
    "Everett",
    "Salem",
    "Westfield",
    "Leominster",
    "Fitchburg",
    "Beverly",
    "Holyoke",
    "Marlborough",
    "Woburn",
    "Chelsea",
    "Quincy Market",
    "Cedar Junction",
    "Plymouth",
    "Gillette Stadium",
    "Castle Island",
    "Charles River",
    "Neponset River",
    "Mashpee",
    "Sharon",
    "Walden",
    "Newbury",
    "Revere",
    "Nahant",
    "Tremont",
    "Forge Park",
    "Windsor Gardens",
    "Hampton Beach",
    "Hull",
    "Nantasket",
    "King Philip",
    "Islington",
    "Ruggles",
    "Endicott",
    "South Station",
    "Blue Hills",
    "Boylston",
    "Haymarket",
    "Jamaicaway",
    "Huntington Ave",
    "Mass Ave",
    "Pike",
    "Morrissey Boulevard",
    "Storrow Drive",
    "Soldiers Field Road",
    "Tremont",
    "VFW Parkway",
    "Washington Street",
    "Old Post Road",
    "Arborway",
    "Landsdowne",
    "Downtown Crossing",
    "Suffolk Downs",
    "Stony Brook",
    "Park Street",
    "Pru",
    "Symphony",
    "Brigham Circle",
    "Cleveland Circle",
    "Chesnut Hill",
    "Ashmont",
    "Jackson Square",
    "Uphams Corner",
    "Chelsea",
    "Arlingto n",
    "Hyde Park",
    "Savin Hill",
    "Copley",
    "Packards Corner",
    "Hynes",
    "Mattapan",
    "Fields Corner",
    "Alewife",
    "Wonderland",
    "Lechmere",
    "Canton",
    "Stoughton",
    "Forest Hills",
    "Silver Line",
    "Brookline",
    "Coolidge Corner",
    "Fresh Pond",
    "Billerica",
    "Lynn",
    "Merrimack",
    "Mystic River",
    "Chicopee",
    "Saugus",
    "Agawam",
    "Quabbin",
    "Jamaica Pond",
    "Arboretum",
    "Great Woods",
    "Dottie Pear",
    "Faneuil Hall",
    "Common",
    "Franklin Park",
    "Brattle",
    "Esplanade",
    "Cape Cod",
    "Nantucket",
    "Martha's Vineyard",
    "Logan"
]